            {
      <%
      _.each(model.properties, function(property){
        var value;
        if(property.type.type === "string"){
          if(property.type.regex) var regEx = new RegExp(property.type.regex,"g");
          else var regEx = new RegExp("^[A-Z]{"+property.type.length+"}$","g");
          value = new scope.randomizer(regEx).gen();
          value = "\""+value+"\"";
        }
        else if(property.type.type === "timestamp"){
          value = Date.now();
        }
        else if((property.type.type === "integer")||(property.type.type === "double")){
          var min = property.type.min;
          var max = property.type.max;
          if((!_.isUndefined(min))&&(!_.isUndefined(max))){
            value =  Math.random() * (max - min) + min;
            if(property.type.type === "integer") value = Math.round(value)
          }
          else if((_.isUndefined(min))&&(!_.isUndefined(max))){
            value = max - Math.random() * 100
            if(property.type.type === "integer") value = Math.round(value)
          }
          else if((!_.isUndefined(min))&&(_.isUndefined(max))){
            value = min + Math.random() * 100
            if(property.type.type === "integer") value = Math.round(value)
          }
          else{
            value = Math.random() * 100;
            if(property.type.type === "integer") value = Math.round(value)
          }
        }
        else if(property.type.type === "geojson"){
          value = '{"type" : "Point", "coordinates" : [125.6, 10.1]}';
        }
        else if(property.type.type === "array"){
          if(property.type.key === 'integer'){
            if(property.type.value === 'string'){
              var regEx = new RegExp("^[A-Z]{20}$","g");
              var randomiser = new scope.randomizer(regEx);
              value = "["+randomizer.gen()+", "+randomizer.gen()+"]";
            }
            else if(property.type.value === 'integer'){
              value = "["+ Math.round(Math.random() * 100) +", "+ Math.round(Math.random() * 100) +" ]";
            }
            else if(property.type.value === 'double'){
              value = "["+ Math.random() * 100 +", "+ Math.random() * 100 +" ]";
            }
            else{
              var found_model = scope.get_model_by_name(scope.model.models, property.type.value);
              value = "["+scope.random_json_builder({model: found_model, scope: scope, include_id: true})+", "
                         +scope.random_json_builder({model: found_model, scope: scope, include_id: true})+"]";
              value = "[]";
            }
          }
        }
        else{
          var found_model = scope.get_model_by_name(scope.model.models, property.type.type);
          value = scope.random_json_builder({model: found_model, scope: scope, include_id: true});
          value = "{}";
        }
      %>
                "<%= property.name %>" : <%= value %>,
      <% }); %>
                "_id" : "someid"
            }